# Generated by Django 2.2.2 on 2019-07-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_description_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description_en',
        ),
    ]
